basePath: /v1
definitions:
  models.Export:
    properties:
      address:
        description: 节点地址
        type: string
      createTime:
        description: 创建时间
        type: integer
      id:
        description: Id
        type: string
      targets:
        description: 节点地址列表
        items:
          type: string
        type: array
      type:
        description: 节点类型
        type: string
    required:
    - address
    - type
    type: object
  resp.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
      more_info:
        type: object
      status:
        type: integer
      type:
        type: string
    type: object
info:
  contact:
    email: leizhou.lin@watrix.ai
    name: API Support
    url: github.com/souliot
  description: Golang api of demo
  termsOfService: github.com/souliot
  title: DevOps 开发文档
  version: v1.0.0
paths:
  /export:
    get:
      consumes:
      - application/json
      description: 获取 Prometheus http_sd_config 的接口
      parameters:
      - description: node type
        in: query
        name: type
        type: string
      - description: node address
        in: query
        name: address
        type: string
      - description: page
        in: query
        name: page
        type: string
      - description: pageSize
        in: query
        name: pageSize
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/resp.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Export'
                  type: array
              type: object
      summary: 获取监控节点列表
      tags:
      - 监控
    post:
      consumes:
      - application/json
      description: 添加 Prometheus http_sd_config 的接口
      parameters:
      - description: 监控节点
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/models.Export'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/resp.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.Export'
              type: object
      summary: 添加监控节点
      tags:
      - 监控
  /export/{type}:
    get:
      consumes:
      - application/json
      description: 获取 Prometheus http_sd_config 的接口
      parameters:
      - description: node type
        in: path
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/resp.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.Export'
              type: object
      summary: 获取监控节点
      tags:
      - 监控
  /metrics:
    get:
      consumes:
      - application/json
      description: 获取用户 Prometheus http_sd_config 的接口
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Export
      tags:
      - 监控暴露
swagger: "2.0"
